title: Dapici - Plog
description: > # this means to ignore newlines until "baseurl:"
  Just a handsome IT student 
  currently pursuing Computer Science Bachelor's degree
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: PHAN DOAN THAI BINH \n aka PHAN JOHN # add your name
author-img: dapiciAvatar.jpg # add your photo
about-author: I am a software developer and also fascinated by Machine Learning. Always hungry to keep learning. # add description
social-twitter: https://twitter.com/thaibinh120702 # add your Twitter handle
social-facebook: binhbip.bom.33 # add your Facebook handle
social-github: binh120702 # add your Github handle
social-linkedin: in/thaibinh120702 # add your Linkedin handle
social-email: thaibinh120702@gmail.com # add your Email address

# Disqus
discus-identifier: dapici # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
